[book]
authors = ["Anant Narayan"]
language = "en"
multilingual = false
src = "src"
title = "Strata"
description = "Documentation for Strata"

[preprocessor.emoji]
renderer = ["html"]

[build]
build-dir = "docs"
create-missing = true

[output.html]
theme = "theme"
default-theme = "tokyonight"
preferred-dark-theme = "tokyonight"
